### PR TITLE
Feature/favicon

### LINKED ISSUE #100: Error on calender view (Add Favicon)
when visiting the calender view the console logs the following error
Method parameter 'roomId': Failed to convert value of type 'java.lang.String' to required type 'long'; For input string: "favicon.ico"]

(might have been fixed by roomId)

### PR DESCRIPTION
**Pull request by Alexander-Klee**
In this PR, a new icon is introduced for Soli, added in the sidebar and as the favicon.
Closes #100

### CODE REVIEW

**Comment by Jan8192** [comment]
I can't seem to find the icon in the sidebar... Is this supposed to be like that? 
image

**Review by Jan8192 — APPROVED** [review]
LGTM! I dont like the positioning of the icon though... But it doesn't really matter... 
image

**Comment by Alexander-Klee** [comment]
ui is not final and @JFronny and i were both of the opinion that you should format the icon properly!

**Comment by JFronny** [comment]
To expand on what @Alexander-Klee said: I recall you were working on a redesign of that component. As such, and because we didn't want to interfere with your work, we kept this change as simple as reasonable.

**Comment by Jan8192** [comment]
That's nice... I wasn't really trying to redesign it though, I was just trying stuff out, will create an issue for that though, now that you mentioned it...

**Pull request merged**
