### PR TITLE
feat: correct redirections for event and booking view

### LINKED ISSUE #26: Request functionality when user has booking marked as "on Request"

### LINKED ISSUE #58: feature: booking creation redirects to the new booking

### PR DESCRIPTION
**Pull request by JFronny**
Closes #58 
Closes #26

### CODE REVIEW

**Comment by JFronny** [comment]
Do we want this?

**Comment by JFronny** [comment]
@Alexander-Klee that is good point. @Jan8192 what do you think? To what screen should we redirect after a booking? If you agree, I'll adjust the behavior implemented here to that.

I have now also implemented collaboration requests here.

**Comment by Jan8192** [comment]
I agree with alex

**Comment by Alexander-Klee** [comment]
LGMT!

**Pull request merged**
