### PR TITLE
feat: added start-/endtime in view_event.jte && improved design

### LINKED ISSUE #88: Terminansicht sollte start-/endzeit anzeigen

### PR DESCRIPTION
**Pull request by ProfessionalStackoverflowAbuser**
closes #88.
grafik

### CODE REVIEW

**Review by JFronny — APPROVED** [review]
LGTM

**Review by JFronny — CHANGES_REQUESTED** [review]
On a closer look, your changes to the classes seem to have broken the centered positioning of the card

**Comment by ProfessionalStackoverflowAbuser** [comment]
looks like that now
grafik

**Review by JFronny — APPROVED** [review]
I'm still not completely happy with this page, especially as it doesn't feel super consistent with the rest of the app and doesn't look right for empty descriptions.
That said, I suppose this is good enough for now.

**Pull request merged**
