### PR TITLE
Improve event visualization

### LINKED ISSUE #56: kolloborative Termine im Calender
- kolloborative Termine sollten gekennzeichnet werden
- Beim erstellen von neuen Terminen über koll. Termine drüberziehen erlauben

### LINKED ISSUE #57: Highlight owned events in calender

### PR DESCRIPTION
**Pull request by JFronny**
This applies some coloring based on the event state (share type, priority, ownership)
The actual design could use some work, but will need to be changed anyway when we introduce a dark theme.

Closes #56
Closes #57

### CODE REVIEW

**Review by Jan8192 — APPROVED** [review]
Apart from the weird green boxes around the events, this looks good to me!
image

**Comment by JFronny** [comment]
Those borders were intended to signify ownership over an event.
I agree that that isn't particularly clear.
Do you have a suggestion for how I could represent them instead?

**Comment by JFronny** [comment]
I don't quite get what you mean.
Perhaps the exact design is better discussed later?

**Comment by Jan8192** [comment]
Yea, maybe its a bad idea... Maybe using badges https://daisyui.com/components/badge/ would solve the problem
We could add something like: "Owned by you" as the text inside the badge

**Comment by Jan8192** [comment]
This does look much better! 
image
I think we should add more contrast to the badges though by coloring them differently

**Comment by ProfessionalStackoverflowAbuser** [comment]
this closes #57.

**Comment by JFronny** [comment]
> I think we should add more contrast to the badges though by coloring them differently

In the process of figuring out this CSS, I have experimented with the other colors DaisyUI provides.
I have found just not using a background color to be the least noisy option.
Do experiment with them yourself, though! It is almost certain I have overlooked something!

**Review by Jan8192 — APPROVED** [review]
LGTM!

**Pull request merged**
